version: "3"

services:
  minecraft:
    image: itzg/minecraft-server:java17
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      MEMORY: "2G"
      VERSION: "1.18"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./data:/data
    restart: always
